# Table of Contents
 <p><div class="lev1 toc-item"><a href="#Additionalnote" data-toc-modified-id="Additionalnote-1"><span class="toc-item-num">1&nbsp;&nbsp;</span>Additionalnote</a></div><div class="lev2 toc-item"><a href="#Additional-Note-(1)" data-toc-modified-id="Additional-Note-(1)-11"><span class="toc-item-num">1.1&nbsp;&nbsp;</span>Additional Note (1)</a></div><div class="lev3 toc-item"><a href="#英語" data-toc-modified-id="英語-111"><span class="toc-item-num">1.1.1&nbsp;&nbsp;</span>英語</a></div><div class="lev3 toc-item"><a href="#日本語訳" data-toc-modified-id="日本語訳-112"><span class="toc-item-num">1.1.2&nbsp;&nbsp;</span>日本語訳</a></div><div class="lev3 toc-item"><a href="#解釈" data-toc-modified-id="解釈-113"><span class="toc-item-num">1.1.3&nbsp;&nbsp;</span>解釈</a></div><div class="lev2 toc-item"><a href="#Additional-Note(2)" data-toc-modified-id="Additional-Note(2)-12"><span class="toc-item-num">1.2&nbsp;&nbsp;</span>Additional Note(2)</a></div><div class="lev3 toc-item"><a href="#英語" data-toc-modified-id="英語-121"><span class="toc-item-num">1.2.1&nbsp;&nbsp;</span>英語</a></div><div class="lev3 toc-item"><a href="#日本語訳" data-toc-modified-id="日本語訳-122"><span class="toc-item-num">1.2.2&nbsp;&nbsp;</span>日本語訳</a></div><div class="lev2 toc-item"><a href="#Additional-Note(3)" data-toc-modified-id="Additional-Note(3)-13"><span class="toc-item-num">1.3&nbsp;&nbsp;</span>Additional Note(3)</a></div><div class="lev3 toc-item"><a href="#英語" data-toc-modified-id="英語-131"><span class="toc-item-num">1.3.1&nbsp;&nbsp;</span>英語</a></div><div class="lev3 toc-item"><a href="#日本語訳" data-toc-modified-id="日本語訳-132"><span class="toc-item-num">1.3.2&nbsp;&nbsp;</span>日本語訳</a></div>

Python machine learning bookのレポジトリの２章のAdditionalnoteを訳してみました。  
https://github.com/rasbt/python-machine-learning-book/blob/master/code/ch02/ch02.ipynb

- Addtional Note1
    - 重みの初期値について
- Additional Note2
    - self.w[0]を加えているコードについての説明
- Additional Note3
    - サンプルのシャップルについて

In [28]:
import numpy as np

# Additionalnote

## Additional Note (1)

### 英語
Please note that the learning rate η (eta) only has an effect on the classification outcome  if the weights are initialized to non-zero values.  
If all the weights are initialized to 0, the learning rate parameter eta affects only the scale of the weight vector but not its direction.  
To have the learning rate influence the classification outcome, the weights need to be initialized to non-zero values.  
The respective lines in the code that need to be changed to accomplish that are highlighted on below:  

```python
   def __init__(self, eta=0.01, n_iter=50, random_seed=1): # add random_seed=1
        ...
        self.random_seed = random_seed # add this line

    def fit(self, X, y):
        ...
        # self.w_ = np.zeros(1 + X.shape[1]) ## remove this line
        rgen = np.random.RandomState(self.random_seed) # add this line
        self.w_ = rgen.normal(loc=0.0, scale=0.01, size=1 + X.shape[1]) # add this line
```

### 日本語訳

学習率η（eta）は、重みがゼロ以外の値に初期化されている場合にのみ、分類結果に影響を与えることに注意してください。
すべての重みが0に初期化されると、学習率パラメータηは重みベクトルの大きさにのみ影響を及ぼし、方向に影響を及ぼしません。  
学習率が分類結果に影響するようにするには、ウェイトを0以外の値に初期化する必要があります。  
変更する必要があるコードの各行は、以下で強調表示されています：


```python
   def __init__(self, eta=0.01, n_iter=50, random_seed=1): # add random_seed=1
        ...
        self.random_seed = random_seed # add this line # シードの設定

    def fit(self, X, y):
        ...
        # self.w_ = np.zeros(1 + X.shape[1]) ## remove this line
        rgen = np.random.RandomState(self.random_seed) # add this line 
        self.w_ = rgen.normal(loc=0.0, scale=0.01, size=1 + X.shape[1]) # add this line # 重みの設定,Xの列数 + 1の長さ
```

### 解釈

重みが全てゼロだと

$(z) = 0$となってしまい、常に$\phi(z) = 1$となってしまう。  
そのため、重みの更新結果は入力されたサンプルのクラスにのみ影響を受けることとなる。  
そのため、重みは、0以外にするのが望ましい

## Additional Note(2)

### 英語 
I received a note by a reader who asked about the net input function:

>On page 27, you describe the code.

> the net_input method simply calculates the vector product wTx
However, there is more than a simple vector product in the code:

> def net_input(self, X):  
    """Calculate net input"""  
    return np.dot(X, self.w_[1:]) + self.w_[0]  
   
> In addition to the dot product, there is an addition. The text does not mention anything about what is this + self.w_[0]
> Can you (or anyone) explain why that's there?

-------

Sorry that I went over that so briefly. The `self.w_[0]` is basically the "threshold" or so-called "bias unit." I simply included the bias unit in the weight vector, which makes the math part easier, but on the other hand, it may make the code more confusing as you mentioned.



Let's say we have a 3x2 dimensional dataset `X` (3 training samples with 2 features). Also, let's just assume we have a weight `2` for feature 1 and a weight `3` for feature 2, and we set the bias unit to `4`. 

```
import numpy as np
>>> bias = 4.
>>> X = np.array([[2., 3.], 
...              [4., 5.], 
...              [6., 7.]])
>>> w = np.array([bias, 2., 3.])
```

In order to match the mathematical notation, we would have to add a vector of 1s to compute the dot-product:

```
>>> ones = np.ones((X.shape[0], 1))
>>> X_with1 = np.hstack((ones, X))
>>> X_with1
>>> np.dot(X_with1, w)
array([ 17.,  27.,  37.])
```

However, I thought that adding a vector of 1s to the training array each time we want to make a prediction would be fairly inefficient. So, instead, we can just "add" the bias unit (`w[0]`) to the do product (it's equivalent, since `1.0 * w_0 = w_0`:

```
>>> np.dot(X, w[1:]) + w[0] 
array([ 17.,  27.,  37.])
```

Maybe it is helpful to walk through the matrix-vector multiplication by hand. E.g.,

```
| 1  2  3 |   | 4 |   | 1*4 + 2*2 + 3*3 |   | 17 |
| 1  4  5 | x | 2 | = | 1*4 + 4*2 + 5*3 | = | 27 |
| 1  6  7 |   | 3 |   | 1*4 + 6*2 + 7*3 |   | 37 |
```

which is the same as

```
| 2  3 |                  | 2*2 + 3*3 |          | 13 + bias |   | 17 |
| 4  5 | x | 2 | + bias = | 4*2 + 5*3 | + bias = | 23 + bias | = | 27 |
| 6  7 |   | 3 |          | 6*2 + 7*3 |          | 33 + bias |   | 37 |

```

### 日本語訳

net_input　メソッドについて、読者から質問を受けた。

> 27ページのコードについて

> net_input メソッドは単にベクトルのドット積 $w^T x$を計算している。  
しかしながら、コードでは、ベクトルのドット積以上のコードとなっている。（self.w_[0]が加えられているが説明がない）  
是非説明をお願いしたい。

> def net_input(self, X):  
    """Calculate net input"""  
    return np.dot(X, self.w_[1:]) + self.w_[0]  
   
> In addition to the dot product, there is an addition. The text does not mention anything about what is this + self.w_[0]
> Can you (or anyone) explain why that's there?

-------

self.w_[0]は閾値とかバイアスと呼ばれる。  
本では、単純に重みベクトルににバイアスを含めましたが、これは数学的な部分を簡単にするが、一方で、質問のようにコードを混乱させるかもしれません。


3行×2列のデータセット「X」（2つの特徴量を有する3つのトレーニングサンプル）があるとしよう。
また、w_1（特徴量１のウェイト）= 2、w_2（特徴量2のウェイト）= 3 w_0（バイアス）= 4に設定します。

In [10]:
bias = 4.
X = np.array([[2.,3.],
             [4.,5.],
             [6.,7.]])
w = np.array([bias,2.,3.])

In [20]:
X_with1

array([[ 1.,  2.,  3.],
       [ 1.,  4.,  5.],
       [ 1.,  6.,  7.]])

In [21]:
# 数学的表記法と一致させるためには、ドット積を計算するために1のベクトルを追加する必要があります。
ones = np.ones((X.shape[0], 1)) # 3*1の列ベクトル
X_with1 = np.hstack((ones, X)) # 3*3の行列（Xの左端にonesを追加）
np.dot(X_with1,w)

array([ 17.,  27.,  37.])

In [22]:
# しかし、予測をする毎に、トレーニング行列に１ベクトルを加えるというのはかなり非効率です。
# その替わりに、ベクトルのドット積に単にバイアス（'w[0]')を加えることができる。（これは1.0*w_0 = w_0なので同等です。）

np.dot(X,w[1:]) + w[0]

array([ 17.,  27.,  37.])

おそらく、手で計算してみるとわかります。例えば、以下の１と２の計算は同等です。

1.
```
| 1  2  3 |   | 4 |   | 1*4 + 2*2 + 3*3 |   | 17 |
| 1  4  5 | x | 2 | = | 1*4 + 4*2 + 5*3 | = | 27 |
| 1  6  7 |   | 3 |   | 1*4 + 6*2 + 7*3 |   | 37 |
```

2.
```
| 2  3 |           　　 　　 　　 　    | 2*2 + 3*3 | 　　　　　    　     | 13 + bias | 　  | 17 |
| 4  5 | x | 2 | + bias = | 4*2 + 5*3 | + bias = | 23 + bias | = | 27 |
| 6  7 |   | 3 |     　　 　　 　　   | 6*2 + 7*3 |      　　　　　    | 33 + bias |  　　 | 37 |

```

## Additional Note(3)

### 英語

For simplicity at this point, we don't talk about shuffling at this point; I wanted to introduce concepts incrementally so that it's not too overwhelming all at once. Since a reader asked me about this, I wanted to add a note about shuffling, which you may want to use if you are using a Perceptron in practice. I borrowed the code from the `AdalineSGD` section below to modify the Perceptron algorithm accordingly (new lines are marked by trailing "`# new`" inline comment):

```python
class Perceptron(object):
    """Perceptron classifier.

    Parameters
    ------------
    eta : float
        Learning rate (between 0.0 and 1.0)
    n_iter : int
        Passes over the training dataset.
    shuffle : bool (default: True)
        Shuffles training data every epoch if True to prevent cycles.
    random_state : int (default: None)
        Set random state for shuffling and initializing the weights.

    Attributes
    -----------
    w_ : 1d-array
        Weights after fitting.
    errors_ : list
        Number of misclassifications in every epoch.

    """
    def __init__(self, eta=0.01, n_iter=10,
                 shuffle=True, random_state=None):  # new
        self.eta = eta
        self.n_iter = n_iter
        self.shuffle = shuffle  # new
        if random_state:  # new
            np.random.seed(random_state)  # new

    def fit(self, X, y):
        """Fit training data.

        Parameters
        ----------
        X : {array-like}, shape = [n_samples, n_features]
            Training vectors, where n_samples is the number of samples and
            n_features is the number of features.
        y : array-like, shape = [n_samples]
            Target values.

        Returns
        -------
        self : object

        """
        self.w_ = np.zeros(1 + X.shape[1])
        self.errors_ = []

        for _ in range(self.n_iter):
            if self.shuffle:  # new
                X, y = self._shuffle(X, y)  # new
            errors = 0
            for xi, target in zip(X, y):
                update = self.eta * (target - self.predict(xi))
                self.w_[1:] += update * xi
                self.w_[0] += update
                errors += int(update != 0.0)
            self.errors_.append(errors)
        return self

    def _shuffle(self, X, y):  # new
        """Shuffle training data"""  # new
        r = np.random.permutation(len(y))  # new
        return X[r], y[r]  # new

    def net_input(self, X):
        """Calculate net input"""
        return np.dot(X, self.w_[1:]) + self.w_[0]

    def predict(self, X):
        """Return class label after unit step"""
        return np.where(self.net_input(X) >= 0.0, 1, -1)
```

### 日本語訳

簡単のために、サンプルのシャッフルについては、この段階では触れていません。  
一気にコンセンプトを導入するのではなく、段階で気に導入したかったためです。  
読者から質問があったので、実際にパーセプトロンを用いる場合に使用するかもしれない、サンプルのシャッフルについて書きます。  
Perceptronアルゴリズムを変更するために、以下の `AdalineSGD`セクションからコードを借りました  
（新しい行には ``＃new` "という行末に印がついています）


```python
class Perceptron(object):
    """Perceptron classifier.

    Parameters
    ------------
    eta : float
        学習率 (between 0.0 and 1.0)
    n_iter : int
        トレーニングデータのトレーニング回数
    shuffle : bool (default: True)
        Trueの場合、エポックごとにシャッフルする
    random_state : int (default: None)
        シャッフルと重みの初期化のための、randam_state(シード)を設定

    属性
    -----------
    w_ : 1次元配列
        適合後の重み
    errors_ : list
        各エポックでの誤分類数
        
    """
    def __init__(self, eta=0.01, n_iter=10,
                 shuffle=True, random_state=None):  # new
        self.eta = eta
        self.n_iter = n_iter
        self.shuffle = shuffle  # new
        if random_state:  # new
            np.random.seed(random_state)  # new

    def fit(self, X, y):
        """Fit training data.

        Parameters
        ----------
        X : {array-like}, shape = [n_samples, n_features]
            Training vectors, where n_samples is the number of samples and
            n_features is the number of features.
        y : array-like, shape = [n_samples]
            Target values.

        Returns
        -------
        self : object

        """
        self.w_ = np.zeros(1 + X.shape[1])
        self.errors_ = []

        for _ in range(self.n_iter):
            if self.shuffle:  # new
                X, y = self._shuffle(X, y)  # new
            errors = 0
            for xi, target in zip(X, y):
                update = self.eta * (target - self.predict(xi))
                self.w_[1:] += update * xi
                self.w_[0] += update
                errors += int(update != 0.0)
            self.errors_.append(errors)
        return self

    def _shuffle(self, X, y):  # new
        """Shuffle training data"""  # new
        r = np.random.permutation(len(y))  # new
        return X[r], y[r]  # new

    def net_input(self, X):
        """Calculate net input"""
        return np.dot(X, self.w_[1:]) + self.w_[0]

    def predict(self, X):
        """Return class label after unit step"""
        return np.where(self.net_input(X) >= 0.0, 1, -1)
```